apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: binance-shared-pvc
  namespace: elk-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
