apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-setup-users
  namespace: elk-stack
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-elasticsearch
        image: curlimages/curl:latest
        command: ['sh', '-c']
        args:
          - |
            echo "Waiting for Elasticsearch to be ready..."
            while ! curl -s -u elastic:${ELASTIC_PASSWORD} http://elasticsearch:9200/_cluster/health; do
              echo "Elasticsearch not ready yet, waiting 10 seconds..."
              sleep 10
            done
            echo "Elasticsearch is ready!"
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elk-credentials
              key: elastic-password
      containers:
      - name: setup-users
        image: curlimages/curl:latest
        command: ['sh', '-c']
        args:
          - |
            echo "Creating user chater..."
            
            # Create the user chater with superuser role
            curl -X POST "http://elasticsearch:9200/_security/user/chater" \
              -u elastic:${ELASTIC_PASSWORD} \
              -H "Content-Type: application/json" \
              -d '{
                "password": "Protel2025!",
                "roles": ["superuser"],
                "full_name": "Chater User",
                "email": "chater@example.com"
              }'
            
            echo ""
            echo "User setup completed!"
            
            # Verify user creation
            echo "Verifying user chater..."
            curl -X GET "http://elasticsearch:9200/_security/user/chater" \
              -u elastic:${ELASTIC_PASSWORD}
            
            echo ""
            echo "Setup completed successfully!"
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elk-credentials
              key: elastic-password
  backoffLimit: 3
